site_name: Teste Super Ensino
dev_addr: 0.0.0.0:8001

nav:
  - Home: 'index.md'
  - API:
    - Questions: 'api/questions.md'
    - Quentions and Answers: 'api/questions_and_answers.md'
    - Resume: 'api/resume.md'
